#!/usr/bin/env bash
# Create a git worktree for WP1 with the untracked credentials files copied
# in. A bare `git worktree add` leaves out wp1/credentials.py.dev (it's
# untracked), and docker-compose-dev.yml bind-mounts that file — when it's
# missing, Docker creates a root-owned directory at its path and the dev
# stack fails to start.
#
# It also writes a worktree-local .env (copied from this checkout's .env if
# present) with a unique COMPOSE_PROJECT_NAME, WP1_SUFFIX, and host-port set
# so the worktree's dev stack can run alongside the main one, remaps the
# port-coupled app config values (WP10DB_PORT, REDIS_PORT, localhost URLs)
# to match, and optionally starts the stack.
#
# Usage: ./create_worktree.sh <branch> [start-point]
#   <branch>       branch to check out in the worktree; created from
#                  [start-point] if it doesn't exist yet
#   [start-point]  ref a new branch is created from (default: main)
#
# The worktree is created at .worktrees/<branch>.
set -euo pipefail

cd "$(dirname "$0")"

branch="${1:?usage: $0 <branch> [start-point]}"
start="${2:-main}"
dest=".worktrees/$branch"

if [ -e "$dest" ]; then
  echo "error: $dest already exists" >&2
  exit 1
fi

if git show-ref --verify --quiet "refs/heads/$branch"; then
  git worktree add "$dest" "$branch"
else
  git worktree add -b "$branch" "$dest" "$start"
fi

# Copy every credentials variant present here but absent from the fresh
# checkout (i.e. the untracked ones; tracked variants already exist there).
copied=0
for f in wp1/credentials.py*; do
  [ -f "$f" ] || continue
  if [ ! -e "$dest/$f" ]; then
    cp -p "$f" "$dest/$f"
    echo "copied $f -> $dest/$f"
    copied=$((copied + 1))
  fi
done

# --- Parallel dev stack config ------------------------------------------
# Pick the smallest port offset N >= 1 not claimed by another worktree's
# .env and whose ports are not currently listening. The main checkout is
# implicitly offset 0 (the defaults in docker-compose-dev.yml).

port_in_use() {
  (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null && { exec 3>&-; return 0; }
  return 1
}

offset_ports() {
  local n="$1"
  echo "$((5000 + n)) $((5173 + n)) $((6300 + n)) $((9736 + n)) \
$((9000 + 2 * n)) $((9001 + 2 * n)) $((2345 + n)) $((8003 + 2 * n)) $((8004 + 2 * n))"
}

used_offsets=$(grep -hs '^# WP1_STACK_OFFSET=' .worktrees/*/.env | cut -d= -f2 || true)

n=1
while :; do
  ok=1
  for u in $used_offsets; do
    [ "$u" = "$n" ] && { ok=0; break; }
  done
  if [ "$ok" = 1 ]; then
    for p in $(offset_ports "$n"); do
      port_in_use "$p" && { ok=0; break; }
    done
  fi
  [ "$ok" = 1 ] && break
  n=$((n + 1))
  if [ "$n" -gt 50 ]; then
    echo "error: no free port offset found (tried 1-50)" >&2
    exit 1
  fi
done

read -r web_port frontend_port db_port redis_port minio_port minio_console_port \
  zimfarm_db_port zimfarm_ui_port zimfarm_api_port <<<"$(offset_ports "$n")"

slug=$(echo "$branch" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')
slug="${slug#-}"; slug="${slug%-}"

# Start from this checkout's .env (app secrets/config), if present, and
# remap the default host ports to this worktree's set. Values the user has
# already customized away from the defaults are left alone.
if [ -f .env ]; then
  sed -e "s/^WP10DB_PORT=6300$/WP10DB_PORT=$db_port/" \
    -e "s/^REDIS_PORT=9736$/REDIS_PORT=$redis_port/" \
    -e "s|localhost:5000|localhost:$web_port|g" \
    -e "s|localhost:5173|localhost:$frontend_port|g" \
    -e "s|localhost:9000|localhost:$minio_port|g" \
    -e "s|localhost:8003|localhost:$zimfarm_ui_port|g" \
    -e "s|localhost:8004|localhost:$zimfarm_api_port|g" \
    .env >"$dest/.env"
  echo "copied .env -> $dest/.env (host ports remapped)"
else
  : >"$dest/.env"
  echo "note: no .env in this checkout; wrote $dest/.env with stack vars only"
fi

cat >>"$dest/.env" <<EOF

# --- Parallel dev stack (generated by create_worktree.sh) ---
# WP1_STACK_OFFSET=$n
COMPOSE_PROJECT_NAME=wp1-dev-$slug
WP1_SUFFIX=-$slug
WP1_WEB_PORT=$web_port
WP1_FRONTEND_PORT=$frontend_port
WP1_DB_PORT=$db_port
WP1_REDIS_PORT=$redis_port
WP1_MINIO_PORT=$minio_port
WP1_MINIO_CONSOLE_PORT=$minio_console_port
WP1_ZIMFARM_DB_PORT=$zimfarm_db_port
WP1_ZIMFARM_UI_PORT=$zimfarm_ui_port
WP1_ZIMFARM_API_PORT=$zimfarm_api_port
EOF

echo "stack: project=wp1-dev-$slug offset=$n web=$web_port frontend=$frontend_port" \
  "db=$db_port redis=$redis_port minio=$minio_port/$minio_console_port"

echo "worktree ready at $dest ($copied credentials file(s) copied)"

if [ -t 0 ]; then
  read -r -p "Start servers now? [Y/n] " answer
  case "$answer" in
    n* | N*) echo "skipped; start later with: (cd $dest && docker compose -f docker-compose-dev.yml up -d --build)" ;;
    *) (cd "$dest" && docker compose -f docker-compose-dev.yml up -d --build) ;;
  esac
else
  echo "non-interactive; start servers with: (cd $dest && docker compose -f docker-compose-dev.yml up -d --build)"
fi
