DROP TABLE IF EXISTS `ratings`;
DROP TABLE IF EXISTS `logging`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `moves`;
DROP TABLE IF EXISTS `projects`;
DROP TABLE IF EXISTS `namespacename`;
DROP TABLE IF EXISTS `releases`;
DROP TABLE IF EXISTS `global_articles`;
DROP TABLE IF EXISTS `global_rankings`;
