version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.9'

# Build from the docs/ directory with Sphinx
mkdocs:
  configuration: mkdocs.yml

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
